version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.CommitDate}}
    mod_timestamp: "{{.CommitTimestamp}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^.github:"
      - "^.vscode:"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: azctx
    repository:
      owner: whiteducksoftware
      name: homebrew-tap
      branch: main
      token: "{{ .Env.AUTH_GITHUB }}"
    dependencies:
      - azure-cli
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: "{{ .Env.GITHUB_ACTOR }}"
      email: "{{ .Env.GITHUB_ACTOR_ID }}+{{ .Env.GITHUB_ACTOR }}@users.noreply.github.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/whiteducksoftware/azctx"
    description: "Faster switching between Azure Subscriptions in your Azure CLI"
    license: "MIT"
    install: |
      bin.install "azctx"

winget:
  - name: azctx
    publisher: "white duck GmbH"
    path: "manifests/w/whiteducksoftware/azctx/{{ .Version }}"
    short_description: "Faster switching between Azure Subscriptions in your Azure CLI"
    license: "mit"
    publisher_url: "https://whiteduck.de/en/"
    publisher_support_url: "https://whiteduck.de/en/contact/"
    package_identifier: whiteducksoftware.azctx
    url_template: "https://github.com/whiteducksoftware/azctx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: "{{ .Env.GITHUB_ACTOR }}"
      email: "{{ .Env.GITHUB_ACTOR_ID }}+{{ .Env.GITHUB_ACTOR }}@users.noreply.github.com"
    commit_msg_template: "WinGet manifest update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/whiteducksoftware/azctx"
    license_url: "https://github.com/whiteducksoftware/azctx/blob/main/LICENSE"
    copyright: "Copyright 2023 white duck GmbH"
    skip_upload: auto
    release_notes: "{{.Changelog}}"
    release_notes_url: "https://github.com/whiteducksoftware/azctx/releases/tag/{{ .Tag }}"
    tags:
      - azure
      - azure-cli
    dependencies:
      - package_identifier: Microsoft.AzureCLI
        minimum_version: 2.50.0
    repository:
      owner: whiteducksoftware
      name: winget-pkgs
      branch: azctx-{{ .Version }}
      token: "{{ .Env.AUTH_GITHUB }}"
      pull_request:
        enabled: false
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
