name: goreleaser-ci

on:
  pull_request:
      branches: [main]

env:
  GO_VERSION: '1.23'

jobs:
  goreleaser-ci-linux:
    name: goreleaser-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"

      # - name: Ensure go.mod is already tidied
      #   run: go mod tidy && git diff --exit-code

      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: lint
        uses: golangci/golangci-lint-action@v6.3.0
        with:
          version: latest

      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --skip publish,snapcraft --clean --config .goreleaser.yaml

  goreleaser-ci-windows:
    name: goreleaser-ci-windows
    needs: goreleaser-ci-linux
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --skip publish,snapcraft --clean --config .goreleaser-windows.yaml
